project:
  type: website
  output-dir: docs
  
website:
  title: ""
  page-navigation: true
  favicon: /assets/img/logo7.png
  search: false
  navbar: 
     background: light
     search: false
     logo: "/assets/img/RWSC_Logo_notext.png"
     bread-crumbs: false
  sidebar:
    title: Data Catalog
    logo: "/assets/img/logo7.png"
    pinned: true
    align: "center"
  page-footer:
    left: "&copy; CC-By-NC-ND RWSC Steering Committee, 2024"
    right: <img src="/assets/img/RWSC_Logo.png" width="125">
  # chapters: 

format:
  html:
    theme:
      - cosmo
      - rwsc.scss
    fontsize: 1.1em
    linestretch: 1.5
    embed-resources: true 
    smooth-scroll: true
    toc: true
    toc-location: left 
    toc-title: " "
    toc-depth: 4
    page-layout: full
    code-link: true
    author-meta: "Regional Wildlife Science Collaborative for Offshore Wind"
    callout-appearance: simple
    link-external-newwindow: true


