# Progress towards understanding the offshore wind and wildlife data landscape and building a Data Catalog

As part of RWSC’s mission to facilitate coordinated research and analysis for wildlife, marine ecosystems, and offshore wind, the [Data Governance Subcommittee](https://rwsc.org/series/rwsc-data-governance-subcommittee/) has been working with other taxa- and habitat-focused RWSC Subcommittees to identify and recommend long-term storage options for each type of data described in [RWSC's Science Plan](https://rwsc.org/science-plan). In addition, entities that fund and/or require offshore wind and wildlife or environmental data collection and research have described a need for simple, long-term storage and access to data that they have funded, as well as easy and centralized public discovery of, and access to, these datasets and research outputs.

To address these needs, RWSC is beginning to build an Offshore Wind & Wildlife Data Catalog to make related data easier to find and reuse. The first step was to build on [NYSERDA’s *Wildlife Data Standardization and Sharing: Environmental Data Transparency for New York State Offshore Wind Energy*][1], and review the >30 data repositories, data access points, and other “data places” described in the RWSC Science Plan, to determine how they accept data, steward data, and support data collaboration. We used [criteria][2]{target="_blank"} developed with RWSC staff and Subcommittee members for this review.

What we found was that many data places people were familiar with did not fully meet our criteria for true data ‘repositories.’ Under that definition, data repositories have to:  
&nbsp; &nbsp; &nbsp; &nbsp; 1. Accept data submissions and provide access for data reuse  
&nbsp; &nbsp; &nbsp; &nbsp; 2. Provide long-term data storage and preservation   
Many of these data places provide other valuable features to the research community, such as aggregating data for searching, but they do not provide a home for the data that can support access and reanalysis over the 30+ year lifetime of a wind farm.

The next step we will take is to scope the requirements and potential platforms for a Data Catalog, in collaboration with the [Northeast Regional Ocean Council (NROC)](https://www.northeastoceancouncil.org), [Mid-Atlantic Regional Council on the Ocean (MARCO)](https://midatlanticocean.org), and [NOAA's National Centers for Coastal Ocean Science (NCCOS)][3]. For this scoping analysis, we have focused on an initial group of repositories  (listed below) that both meet the criteria above and include and share minimum metadata that could connect to the Offshore Wind & Wildlife Data Catalog. We think these repositories are most likely to be compatible, and will be used to prototype the Data Catalog. Where repositories have member nodes that are commonly used by the offshore wind and wildlife community, we have listed those as well.

We will also be continuing our repository review this fall, including follow-up discussions with staff at other data programs --  such as the Integrated Ocean Observing System (IOOS), Ocean Biodiversity Information System (OBIS), OBIS-SEAMAP, and National Centers for Environmental Information (NCEI) --  to determine how they handle data submissions and storage, how they can be connected to the Data Catalog, and to provide additional guidance to data submitters. We plan to release an updated version of this list in December 2024.

### Initial Repositories under consideration for the Offshore Wind & Wildlife Data Catalog 

+-------------------------------+----------------------------------------------------------------------------------------------+
| Data type                     | Repositories                                                                                 |
+===============================+==============================================================================================+
| Animal tracking data          | [Movebank][4]                                                                                |
+-------------------------------+----------------------------------------------------------------------------------------------+
| Telemetry data                | [Ocean Tracking Network][5] and compatible nodes                                             |
|                               |                                                                                              |
|                               | -   [ACT-MATOS][6]                                                                           |
|                               |                                                                                              |
|                               | [Motus][7]                                                                                   |
|                               |                                                                                              |
|                               | [Animal Telemetry Network][8]                                                                |
+-------------------------------+----------------------------------------------------------------------------------------------+
| Acoustic data                 | [Passive Acoustic Data Archive][9]                                                           |
|                               |                                                                                              |
|                               | [North American Bat Monitoring Program][10]                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------+
| Bat observations              | [North American Bat Monitoring Program][10]                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------+
| Plankton and chlorophyll data | [Environmental Data Initiative][11]                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------+
| Genetic sequence data         | [National Center for Biotechnology Information][12]                                          |
+-------------------------------+----------------------------------------------------------------------------------------------+

[1]: <https://www.nyserda.ny.gov/-/media/Project/Nyserda/files/Programs/offshore-wind/21-11-Wildlife-Data-Standardization-and-Sharing-Environmental-Data-Transparency-for-NYS-OSW-Energy.pdf>
[2]: </assets/pdfs/RWSC_Criteria_for_Recommending_Repositories.pdf>
[3]: <https://coastalscience.noaa.gov/>
[4]: <https://datarepository.movebank.org/home>
[5]: <https://oceantrackingnetwork.org/data-centre/>
[6]: <https://matos.asascience.com/>
[7]: <https://motus.org/explore/>
[8]: <https://atn.ioos.us/>
[9]: <https://www.ncei.noaa.gov/products/passive-acoustic-data>
[10]: <https://sciencebase.usgs.gov/nabat/#/about>
[11]: <https://edirepository.org/>
[12]: <https://www.ncbi.nlm.nih.gov/>



